name: deploy
on:
  workflow_dispatch:

jobs:
  deploy_ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: prepare env
        run: cp ${ENV:-'.github/.env.staging'} .env

      - name: build
        run: npm run build

      - name: pinata
        id: pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
          PIN_ALIAS: staging
        run: node scripts/pin-pinata.js

      - name: crust
        uses: crustio/ipfs-crust-action@f51bf12d352d230e12bfd8fa00b07f1f6c7aa735
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.pinata.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}
