name: deploy
on:
  workflow_dispatch:

jobs:
  pin_on_crust:
    name: Pin on Crust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Upload
        uses: crustio/ipfs-upload-action@v1.0.2
        id: uploadsite
        with:
          path: './'
          crust-secret-key: ${{ secrets.CRUST_SECRET_KEY }}
      
      - name: Pin to Crust
        id: pintocrust
        uses: crustio/ipfs-crust-action@v1.0.8
        with:
          cid: ${{ steps.uploadsite.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}
